theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: false
  logo:
    header: "/assets/images/rosebush.svg"
    footer: "/assets/images/clemence.svg"
  breadcrumb:
    position: after-hero
  home:
    head:
      title: site